services:
  - type: web
    name: fynanpro
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python run.py"
    plan: free
    envVars:
      - key: SECRET_KEY
        value: "sua-chave-secreta-muito-segura-aqui-123456789"
      - key: FLASK_ENV
        value: "production"