services:
  - type: web
    name: fynanpro
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: starter
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        generateValue: false
