services:
  - type: web
    name: fynanpro-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    envVars:
      - key: SECRET_KEY
        value: "fynanpro-secret-key-2025-ultra-secure"
      - key: FLASK_ENV
        value: "production"